### ISSUE TITLE
AccessTokenLifetime is not working.

### ISSUE THREAD

**Issue by sub318** [MicrosoftDocs/azure-docs.ko-kr#1058]
I did set AccessTokenLifetime but this is not working.
I wants access token lifetime to increase.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 10b999ad-7029-0ad0-754e-00437e7ae571
* Version Independent ID: a1994e2e-cac8-8467-39b1-2b2d707c032c
* Content: [Azure Active Directory에서 구성 가능한 토큰 수명 - Microsoft identity platform](https://docs.microsoft.com/ko-kr/azure/active-directory/develop/active-directory-configurable-token-lifetimes)
* Content Source: [articles/active-directory/develop/active-directory-configurable-token-lifetimes.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/active-directory/develop/active-directory-configurable-token-lifetimes.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by srvbpigh** [comment]
Hello, @sub318
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Hello, @sub318 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43507.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
