### ISSUE TITLE
dataset url is not valid

### ISSUE THREAD

**Issue by jsrimr** [MicrosoftDocs/azure-docs.ko-kr#1060]
cannot load dataset from "https://automldemods.blob.core.windows.net/datasets/PlayaEvents2016,_1.6MB,_3.4k-rows.cleaned.2.tsv"

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 585fff5e-cadd-8967-8c09-63d8afcb53b3
* Version Independent ID: 95274303-b152-2ee8-113e-e0763beca7ed
* Content: [자동화 된 ML 실험 만들기 - Azure Machine Learning](https://docs.microsoft.com/ko-kr/azure/machine-learning/service/how-to-configure-auto-train#feedback)
* Content Source: [articles/machine-learning/service/how-to-configure-auto-train.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/machine-learning/service/how-to-configure-auto-train.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @cartacioS
* Microsoft Alias: **sacartac**

**Comment by srvbpigh** [comment]
Hello, @jsrimr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @jsrimr, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/45064. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
