### ISSUE TITLE
Key Vault Name is correct but 502.5 Error Return..

### ISSUE THREAD

**Issue by yourera** [MicrosoftDocs/azure-docs.ko-kr#229]
i was doing same this document but, 502.5 error return..
this document said, if 502.5 error ,check your key vault name is correct .
but My code is same my key vault name.

how i can solve this error

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 9741f71e-5257-f7cb-cf78-701ceb609230
* Version Independent ID: 9d4c200e-2133-bf4e-7b60-631e328eb1af
* Content: [Key Vault에서 비밀을 읽도록 Azure 웹 응용 프로그램 구성 자습서](https://docs.microsoft.com/ko-kr/azure/key-vault/tutorial-web-application-keyvault#open-azure-cloud-shell)
* Content Source: [articles/key-vault/tutorial-web-application-keyvault.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/key-vault/tutorial-web-application-keyvault.md)
* Service: **key-vault**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #15500](https://github.com/MicrosoftDocs/azure-docs/issues/15500) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @yourera 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/15500.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
