### ISSUE TITLE
A bug in the code

### ISSUE THREAD

**Issue by syhuh** [MicrosoftDocs/azure-docs.ko-kr#323]
There is a bug in the code of 'View the results' section

' for p in predictions[0]:' should be 'for p in predictions:'

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 754dd7d5-dd8b-4a75-5d79-0ba621a847cd
* Version Independent ID: 3cca3535-1c16-2da1-46c6-421cbf808bc3
* Content: [자습서: Python으로 TensorFlow 모델 실행 - Custom Vision Service](https://docs.microsoft.com/ko-kr/azure/cognitive-services/custom-vision-service/export-model-python#view-the-results)
* Content Source: [articles/cognitive-services/Custom-Vision-Service/export-model-python.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/live/articles/cognitive-services/Custom-Vision-Service/export-model-python.md)
* Service: **cognitive-services**
* GitHub Login: @areddish
* Microsoft Alias: **areddish**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25967](https://github.com/MicrosoftDocs/azure-docs/issues/25967) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @syhuh 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/25967

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
