### ISSUE TITLE
connection type

### ISSUE THREAD

**Issue by eunjisson** [MicrosoftDocs/azure-docs.ko-kr#658]
I tried to get current connection policy by PowerShell & Azure CLI. I can't show this configuration value. 
Please add script to get current connection and change connection settings via PowerShell & Azure CLI like Azure SQL Connectivity Architecture. (https://docs.microsoft.com/en-us/azure/sql-database/sql-database-connectivity-architecture)

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: fc2dd547-3ff7-b32a-ba8a-c582a721a0ee
* Version Independent ID: f083bdda-0c66-af32-0d27-f535e46c96dc
* Content: [Azure SQL Database에서 관리 되는 인스턴스에 대 한 연결 아키텍처](https://docs.microsoft.com/ko-kr/azure/sql-database/sql-database-managed-instance-connectivity-architecture#feedback)
* Content Source: [articles/sql-database/sql-database-managed-instance-connectivity-architecture.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/sql-database/sql-database-managed-instance-connectivity-architecture.md)
* Service: **sql-database**
* Sub-service: **managed-instance**
* GitHub Login: @srdan-bozovic-msft
* Microsoft Alias: **srbozovi**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32505](https://github.com/MicrosoftDocs/azure-docs/issues/32505) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @eunjisson 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/32505

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
