### ISSUE TITLE
PDF download with proper language

### ISSUE THREAD

**Issue by hanchoi** [MicrosoftDocs/azure-docs.ko-kr#969]
When "reading in English toggle" enabled, I hope I could download PDF file written in English even though the page is under /ko-kr/ path

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 0767aac4-fcd9-eaac-2c30-8f17d8eadd92
* Version Independent ID: a380a828-03f9-e037-3a62-e4165fda7cb6
* Content: [관리자 역할 설명 및 사용 권한 - Azure Active Directory](https://docs.microsoft.com/ko-kr/azure/active-directory/users-groups-roles/directory-assign-admin-roles#feedback)
* Content Source: [articles/active-directory/users-groups-roles/directory-assign-admin-roles.md](https://github.com/MicrosoftDocs/azure-docs.ko-kr/blob/master/articles/active-directory/users-groups-roles/directory-assign-admin-roles.md)
* Service: **active-directory**
* Sub-service: **users-groups-roles**
* GitHub Login: @curtand
* Microsoft Alias: **curtand**

**Comment by srvbpigh** [comment]
Hello, @hanchoi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@ishasahni1 can you please check this issue? It refers to the site functionality

**Comment by ishasahni1** [comment]
@hanchoi thank you so much for your valuable feedback. This is by design, as toggle Feature can be used when customer is not quite clear with localized content so they can switch and read text in en-us. Where as PDF generation is based on the url settings up on the node. 

We will surely share your feedback with engineering team and request them to look into it.

@ceciac
